baseURL = 'https://tech.kloom.io'
copyright = "{year}" # To make 2007 - 2022. Just add before {year} example: 2007 - {year}
languageCode = 'ko-KR'
defaultContentLanguage = 'kr'
theme = 'enchanted-lowkey'
title = 'Hello! Kloom Tech'
enableRobotsTXT = true
summaryLength = 15
paginate = 5
ignoreLogs = ['warning-goldmark-raw-html']

[permalinks]
  blog = "/:year/:month/:title/"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4